FROM python:3.11-alpine

LABEL maintainer="bxian@my.bcit.ca"

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python3", "app.py" ]